name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: task-manager-391018

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          version: '324.0.0'
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet

